use  customer_behavior;
select *from dbo.customer;
select count(*) from dbo.customer;
select top 5 *from dbo.customer;
--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as revenue from dbo.customer group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount 
from dbo.customer 
where discount_applied='yes'and purchase_amount > = (select avg(purchase_amount) from dbo.customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select count(*) as total_customers
from dbo.customer 
where discount_applied='yes'and purchase_amount > = (select avg(purchase_amount) from dbo.customer);



select top 5 item_purchased,avg(review_rating) as average_review_rating
from dbo.customer
group by item_purchased
order by avg(review_rating) desc
 ;
 select item_purchased,round(avg(review_rating),2) as average_review_rating
from dbo.customer
group by item_purchased
order by avg(review_rating) desc
 offset 0 rows
 fetch next 5 rows only;

 --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

 select shipping_type,
 avg(purchase_amount)as amount
 from dbo.customer
 where shipping_type in ('express','standard')
 group by shipping_type;

 --Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

 select subscription_status,
 avg(purchase_amount)as spend,
 sum(purchase_amount) as revenue
 from dbo.customer
 group by subscription_status
 order by avg(purchase_amount), sum(purchase_amount) desc;

select subscription_status,
 count(customer_id) as total_cutomers,
 avg(purchase_amount)as spend,
 sum(purchase_amount) as revenue
 from dbo.customer
 group by subscription_status
 order by spend, revenue desc;

 --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 select top 5 item_purchased ,
100* sum(case when discount_applied='yes'then 1 else 0 end)/count(*) as discount_rate
 from dbo.customer
 group by item_purchased
 order by discount_rate desc;

 --Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

 with customer_type as(select customer_id , previous_purchases 
 ,case 
      when previous_purchases = 1 then 'new'
      when previous_purchases between 2 and 10 then 'returing'
	  else 'loyal'
	  end as customer_segment from dbo.customer)
select customer_segment,count(*) as total_customer from customer_type
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

with item_count as(select item_purchased,category,count(customer_id) as total_orders, 
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from dbo.customer
group by category,item_purchased)
select category,item_purchased,item_rank, total_orders
from item_count
where item_rank<=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id) as total_customers
from dbo.customer
where previous_purchases>5 
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select age_group,sum(purchase_amount) as revenue
from dbo.customer
group by age_group
order by revenue desc;